# Default Spring Boot application properties
# Only non-sensitive, non-environment-specific defaults here
server.port=8080
spring.profiles.active=test

#JWT
jwt.secret=k2L8rIUVf+TTPT04A92hoaN4gE4QXZ4IYdaKl/MBa5vCexiTfp3JWurRkhP6t6K15RxX9OpMihfN0VH/dsPneg==
jwt.expiration=3600000

# Swagger UI configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.version=2.6.7
